ARG GANLANZHIPINGDADING
FROM $GANLANZHIPINGDADING
LABEL maintainer ="zhoujd@hotmail.co.jp"
ADD target/zackback-0.0.1-SNAPSHOT.jar dpj-backed.jar
EXPOSE 9600
ENTRYPOINT ["java","-jar","dpj-backed.jar"]